//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionControl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisionControl.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于... 的本地化字符串。
        /// </summary>
        internal static string RtAboutButton {
            get {
                return ResourceManager.GetString("RtAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 {0} 的本地化字符串。
        /// </summary>
        internal static string RtAboutTitle {
            get {
                return ResourceManager.GetString("RtAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string RtAccept {
            get {
                return ResourceManager.GetString("RtAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string RtAdministrator {
            get {
                return ResourceManager.GetString("RtAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 {1} 版本的“Cognex 应用程序向导”在 {0} 上生成的应用程序 的本地化字符串。
        /// </summary>
        internal static string RtAppGeneratedInfo {
            get {
                return ResourceManager.GetString("RtAppGeneratedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序选项... 的本地化字符串。
        /// </summary>
        internal static string RtAppOptions {
            get {
                return ResourceManager.GetString("RtAppOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序选项 的本地化字符串。
        /// </summary>
        internal static string RtAppOptionsTitle {
            get {
                return ResourceManager.GetString("RtAppOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string RtCancel {
            get {
                return ResourceManager.GetString("RtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择工程 的本地化字符串。
        /// </summary>
        internal static string RtChoseButton {
            get {
                return ResourceManager.GetString("RtChoseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除历史队列 的本地化字符串。
        /// </summary>
        internal static string RtClearQueues {
            get {
                return ResourceManager.GetString("RtClearQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置... 的本地化字符串。
        /// </summary>
        internal static string RtConfigurationButton {
            get {
                return ResourceManager.GetString("RtConfigurationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string RtConfigurationTitle {
            get {
                return ResourceManager.GetString("RtConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码: 的本地化字符串。
        /// </summary>
        internal static string RtConfirmPassword {
            get {
                return ResourceManager.GetString("RtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 IO 状态: 的本地化字符串。
        /// </summary>
        internal static string RtCurrentIOState {
            get {
                return ResourceManager.GetString("RtCurrentIOState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前登录: 的本地化字符串。
        /// </summary>
        internal static string RtCurrentLogin {
            get {
                return ResourceManager.GetString("RtCurrentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;无: 正在使用默认密码&gt; 的本地化字符串。
        /// </summary>
        internal static string RtDefaultPasswords {
            get {
                return ResourceManager.GetString("RtDefaultPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用图像显示 的本地化字符串。
        /// </summary>
        internal static string RtEnableDisplay {
            get {
                return ResourceManager.GetString("RtEnableDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在应用程序启动时上线 的本地化字符串。
        /// </summary>
        internal static string RtEnableIOAtStartup {
            get {
                return ResourceManager.GetString("RtEnableIOAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 {0} 的密码 的本地化字符串。
        /// </summary>
        internal static string RtEnterPassword {
            get {
                return ResourceManager.GetString("RtEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string RtError {
            get {
                return ResourceManager.GetString("RtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 .vpp 文件时发生意外错误: 的本地化字符串。
        /// </summary>
        internal static string RtErrorLoadingVpp {
            get {
                return ResourceManager.GetString("RtErrorLoadingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 .vpp 文件 ({0}) 时发生意外错误: 的本地化字符串。
        /// </summary>
        internal static string RtErrorSavingVpp {
            get {
                return ResourceManager.GetString("RtErrorSavingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业正在运行，无法保存 Vpp 文件。 的本地化字符串。
        /// </summary>
        internal static string RtErrorSavingVpp_Running {
            get {
                return ResourceManager.GetString("RtErrorSavingVpp_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示选项 的本地化字符串。
        /// </summary>
        internal static string RtGroupDisplayOptions {
            get {
                return ResourceManager.GetString("RtGroupDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO 选项 的本地化字符串。
        /// </summary>
        internal static string RtGroupIOOptions {
            get {
                return ResourceManager.GetString("RtGroupIOOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列选项 的本地化字符串。
        /// </summary>
        internal static string RtGroupQueueOptions {
            get {
                return ResourceManager.GetString("RtGroupQueueOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 发生图像队列溢位 的本地化字符串。
        /// </summary>
        internal static string RtImageQueueOverrun {
            get {
                return ResourceManager.GetString("RtImageQueueOverrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效密码 的本地化字符串。
        /// </summary>
        internal static string RtInvalidPassword {
            get {
                return ResourceManager.GetString("RtInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的密码不正确。 的本地化字符串。
        /// </summary>
        internal static string RtInvalidPassword2 {
            get {
                return ResourceManager.GetString("RtInvalidPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码文件 {0} 无效 的本地化字符串。
        /// </summary>
        internal static string RtInvalidPasswordFile {
            get {
                return ResourceManager.GetString("RtInvalidPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时图像 的本地化字符串。
        /// </summary>
        internal static string RtLiveImageButton {
            get {
                return ResourceManager.GetString("RtLiveImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有额外的详细信息。 的本地化字符串。
        /// </summary>
        internal static string RtNoDetails {
            get {
                return ResourceManager.GetString("RtNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;无&gt; 的本地化字符串。
        /// </summary>
        internal static string RtNoFile {
            get {
                return ResourceManager.GetString("RtNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string RtOffline {
            get {
                return ResourceManager.GetString("RtOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string RtOK {
            get {
                return ResourceManager.GetString("RtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string RtOnline {
            get {
                return ResourceManager.GetString("RtOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试打开 {0} 时发生错误: 的本地化字符串。
        /// </summary>
        internal static string RtOpenFileError {
            get {
                return ResourceManager.GetString("RtOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        internal static string RtOperator {
            get {
                return ResourceManager.GetString("RtOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        internal static string RtPassword {
            get {
                return ResourceManager.GetString("RtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickBuild... 的本地化字符串。
        /// </summary>
        internal static string RtQuickBuild {
            get {
                return ResourceManager.GetString("RtQuickBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickBuild 的本地化字符串。
        /// </summary>
        internal static string RtQuickBuildTitle {
            get {
                return ResourceManager.GetString("RtQuickBuildTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        internal static string RtReject {
            get {
                return ResourceManager.GetString("RtReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;不可用&gt; 的本地化字符串。
        /// </summary>
        internal static string RtResultNotAvailable {
            get {
                return ResourceManager.GetString("RtResultNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续运行 的本地化字符串。
        /// </summary>
        internal static string RtRunContinuouslyButton {
            get {
                return ResourceManager.GetString("RtRunContinuouslyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单次运行 的本地化字符串。
        /// </summary>
        internal static string RtRunOnceButton {
            get {
                return ResourceManager.GetString("RtRunOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存... 的本地化字符串。
        /// </summary>
        internal static string RtSaveSettingsButton {
            get {
                return ResourceManager.GetString("RtSaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将当前 QuickBuild 设置写入 {0}？ 的本地化字符串。
        /// </summary>
        internal static string RtSaveSettingsText {
            get {
                return ResourceManager.GetString("RtSaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将当前 QuickBuild 设置写入 {0}？如果选择“否”，则可以在稍后使用 {1} 按钮保存这些设置。 的本地化字符串。
        /// </summary>
        internal static string RtSaveSettingsTextAfterConfig {
            get {
                return ResourceManager.GetString("RtSaveSettingsTextAfterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        internal static string RtSaveSettingsTitle {
            get {
                return ResourceManager.GetString("RtSaveSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置密码... 的本地化字符串。
        /// </summary>
        internal static string RtSetPasswords {
            get {
                return ResourceManager.GetString("RtSetPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置密码 的本地化字符串。
        /// </summary>
        internal static string RtSetPasswordsTitle {
            get {
                return ResourceManager.GetString("RtSetPasswordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误: 的本地化字符串。
        /// </summary>
        internal static string RtStatsAcqErrorCount {
            get {
                return ResourceManager.GetString("RtStatsAcqErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溢位: 的本地化字符串。
        /// </summary>
        internal static string RtStatsAcqOverrunCount {
            get {
                return ResourceManager.GetString("RtStatsAcqOverrunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取相结果 的本地化字符串。
        /// </summary>
        internal static string RtStatsAcquisitionResultsGroup {
            get {
                return ResourceManager.GetString("RtStatsAcquisitionResultsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计取相: 的本地化字符串。
        /// </summary>
        internal static string RtStatsAcquisitions {
            get {
                return ResourceManager.GetString("RtStatsAcquisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobAcceptCount {
            get {
                return ResourceManager.GetString("RtStatsJobAcceptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobErrorCount {
            get {
                return ResourceManager.GetString("RtStatsJobErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计迭代量: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobIterations {
            get {
                return ResourceManager.GetString("RtStatsJobIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobRejectCount {
            get {
                return ResourceManager.GetString("RtStatsJobRejectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业结果 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobResultsGroup {
            get {
                return ResourceManager.GetString("RtStatsJobResultsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业吞吐量: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobThroughput {
            get {
                return ResourceManager.GetString("RtStatsJobThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业吞吐量 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobThroughputGroup {
            get {
                return ResourceManager.GetString("RtStatsJobThroughputGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告: 的本地化字符串。
        /// </summary>
        internal static string RtStatsJobWarningCount {
            get {
                return ResourceManager.GetString("RtStatsJobWarningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string RtStatsNA {
            get {
                return ResourceManager.GetString("RtStatsNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业统计信息 的本地化字符串。
        /// </summary>
        internal static string RtStatsPageTitle {
            get {
                return ResourceManager.GetString("RtStatsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        internal static string RtStatsPercent {
            get {
                return ResourceManager.GetString("RtStatsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每秒 的本地化字符串。
        /// </summary>
        internal static string RtStatsPerSecond {
            get {
                return ResourceManager.GetString("RtStatsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位统计信息 的本地化字符串。
        /// </summary>
        internal static string RtStatsReset {
            get {
                return ResourceManager.GetString("RtStatsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位所有作业的统计信息 的本地化字符串。
        /// </summary>
        internal static string RtStatsResetAll {
            get {
                return ResourceManager.GetString("RtStatsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计吞吐量: 的本地化字符串。
        /// </summary>
        internal static string RtStatsThroughput {
            get {
                return ResourceManager.GetString("RtStatsThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大: 的本地化字符串。
        /// </summary>
        internal static string RtStatsThroughputMax {
            get {
                return ResourceManager.GetString("RtStatsThroughputMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小: 的本地化字符串。
        /// </summary>
        internal static string RtStatsThroughputMin {
            get {
                return ResourceManager.GetString("RtStatsThroughputMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等候... 的本地化字符串。
        /// </summary>
        internal static string RtStatsWaiting {
            get {
                return ResourceManager.GetString("RtStatsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string RtStopButton {
            get {
                return ResourceManager.GetString("RtStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ch (中文) 的本地化字符串。
        /// </summary>
        internal static string RtStringLanguage {
            get {
                return ResourceManager.GetString("RtStringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主管 的本地化字符串。
        /// </summary>
        internal static string RtSupervisor {
            get {
                return ResourceManager.GetString("RtSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统“离线” 的本地化字符串。
        /// </summary>
        internal static string RtSystemOffline {
            get {
                return ResourceManager.GetString("RtSystemOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统“在线” 的本地化字符串。
        /// </summary>
        internal static string RtSystemOnline {
            get {
                return ResourceManager.GetString("RtSystemOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string RtTemplateName {
            get {
                return ResourceManager.GetString("RtTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意外错误 - 的本地化字符串。
        /// </summary>
        internal static string RtUnexpectedErrorQB {
            get {
                return ResourceManager.GetString("RtUnexpectedErrorQB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 包含一个无法初始化的取相配置(原因可能是: 缺少照相机或取相板卡、硬件正在使用或安全性冲突)。请在运行作业之前纠正问题或重新配置取相属性。 的本地化字符串。
        /// </summary>
        internal static string RtUninitializedAcq {
            get {
                return ResourceManager.GetString("RtUninitializedAcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 about.txt 文件: 的本地化字符串。
        /// </summary>
        internal static string RtUsingAbout {
            get {
                return ResourceManager.GetString("RtUsingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 passwords.txt 文件: 的本地化字符串。
        /// </summary>
        internal static string RtUsingPasswords {
            get {
                return ResourceManager.GetString("RtUsingPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 .vpp 文件: 的本地化字符串。
        /// </summary>
        internal static string RtUsingVpp {
            get {
                return ResourceManager.GetString("RtUsingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 Vpp 文件（{0} 或 {1}）。 的本地化字符串。
        /// </summary>
        internal static string RtVppNotFound {
            get {
                return ResourceManager.GetString("RtVppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string RtWarning {
            get {
                return ResourceManager.GetString("RtWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Run_Once {
            get {
                object obj = ResourceManager.GetObject("Run_Once", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
